import json
import uuid
from pathlib import Path
from typing import Dict, Any, Optional, List

# --- Core LangChain Imports ---
from langchain_core.load import dumpd, load

# --- Project Imports ---
from .graph_builder import create_agent_graph, ConversationState
from .tool_provider import ToolProvider
from .vectorstore_manager import get_vector_store_manager
from .agent_monitor import AgentMonitor
from .database import SessionDatabase

from langchain_core.messages import AIMessage, HumanMessage, ToolMessage
from datetime import datetime

class AgentRuntime:
    """
    Manages the entire lifecycle of a directory-scoped agent, acting as the
    central controller that assembles all necessary components.
    """

    def __init__(self, root_dir: str, name: Optional[str] = None,
                 provider: str = "gemini", system_prompt: str = None):
        
        self.root_dir = Path(root_dir).resolve()
        
        # All Jerry-related files go in a hidden .jerry folder
        self.jerry_dir = self.root_dir / ".jerry"
        self.config_path = self.jerry_dir / "config.json"
        self.session_db_path = self.jerry_dir / "sessions.db"
        self.log_db_path = self.jerry_dir / "logs.db"
        self.chroma_dir = self.jerry_dir / ".chroma"
        self.log_dir = self.jerry_dir / "logs"
        
        # The workspace is the root directory itself (no subdirectory)
        self.workspace_dir = self.root_dir

        if not self.jerry_dir.exists():
            self._create_new_agent_scaffold(name=name or self.root_dir.name,
                                 provider=provider,
                                 system_prompt=system_prompt)

        # Load configuration
        with open(self.config_path, "r", encoding="utf-8") as f:
            self.config: Dict[str, Any] = json.load(f)

        if name and self.config.get("name") != name:
            self.config["name"] = name
            with open(self.config_path, "w", encoding="utf-8") as f:
                json.dump(self.config, f, indent=2)
        
        # Initialize session database
        self.session_db = SessionDatabase(self.session_db_path)
        
        # Create or resume session
        self.session_id = str(uuid.uuid4())
        self.session_db.create_session(self.session_id, self.config.get("name", "unnamed_agent"))
        
        # Initialize state from database
        self.state: ConversationState = {"messages": []}

        # --- Instantiate monitoring and logging --- 
        self.log_dir.mkdir(exist_ok=True)
        self.monitor = AgentMonitor(
            agent_name=self.config.get("name", "unnamed_agent"),
            log_dir=self.log_dir,
            session_id=self.session_id,
            log_db_path=self.log_db_path
        )
        self.monitor.log_event("agent_startup", {"config": self.config})

        # --- Instantiate the VectorStoreManager ---
        self.vector_store_manager = get_vector_store_manager(
            persist_directory=self.chroma_dir,
            collection_name=self.config.get("name", "default_agent_collection"),
            monitor=self.monitor
        )
        
        # --- Index documents on startup ---
        self.vector_store_manager.add_documents_from_path(self.workspace_dir)

        # --- Assemble the agent's graph ---
        self.graph = self._initialize_graph()

    # ==========================================================================
    # --- PUBLIC API METHODS ---
    # ==========================================================================

    def invoke(self, input_text: str) -> Dict[str, Any]:
        """
        Handles a single turn of the conversation.
        """
        user_message = HumanMessage(content=input_text)
        self.state["messages"].append(user_message)
        self.session_db.add_message(self.session_id, user_message)
        
        # Track number of messages before graph invocation
        initial_count = len(self.state["messages"])
        
        final_state = self.graph.invoke(self.state)
        self.state = final_state
        
        # Save only new messages generated by the graph
        new_messages = final_state.get("messages", [])[initial_count:]
        for msg in new_messages:
            self.session_db.add_message(self.session_id, msg)
        
        last_ai_message = next((m for m in reversed(final_state.get("messages", [])) if isinstance(m, AIMessage)), None)
        response_text = last_ai_message.content if last_ai_message else "No response."
        
        return {
            "response": response_text,
            "tool_results": final_state.get("tool_results"),
            "used_sources": final_state.get("used_sources")
        }

    def analyze_knowledge_base(self) -> Dict[str, Any]:
        """
        Performs and returns an analysis of the agent's knowledge base.
        """
        return self.monitor.get_knowledge_base_analysis(self.workspace_dir, self.vector_store_manager)

    def shutdown(self) -> Dict[str, Any]:
        """
        Performs all shutdown tasks for the agent.
        """
        self.monitor.log_event("agent_shutdown_start", {})
        self._archive_session_as_markdown()
        self._clear_persistent_state()
        
        final_metrics = self.monitor.get_token_metrics()
        self.monitor.log_event("agent_shutdown_complete", {"final_token_metrics": final_metrics})
        
        return {
            "message": "Session archived, state cleared, and final metrics logged.",
            "final_metrics": final_metrics
        }

    def get_config(self) -> Dict[str, Any]:
        """Returns the agent's configuration dictionary."""
        return self.config

    def reindex_workspace(self) -> Dict[str, int]:
        """Rescans the workspace and updates the knowledge base."""
        return self.vector_store_manager.add_documents_from_path(self.workspace_dir)

    def get_session_history(self) -> str:
        """Returns a formatted string of the current session's history from database."""
        messages = self.session_db.get_session_messages(self.session_id)
        
        if not messages:
            return "No messages in this session yet."
        
        history_str = "" 
        for msg in messages:
            if isinstance(msg, HumanMessage):
                history_str += f"\n--- You ---\n{msg.content}"
            elif isinstance(msg, AIMessage):
                history_str += f"\n--- Agent ---\n{msg.content}"
            elif isinstance(msg, ToolMessage):
                tool_id = getattr(msg, 'tool_call_id', 'unknown')
                history_str += f"\n--- Tool Output ({tool_id}) ---\n{msg.content}"
        return history_str

    # ==========================================================================
    # --- INTERNAL & SETUP METHODS ---
    # ==========================================================================

    def _clear_persistent_state(self):
        """Clears the current session messages from the database."""
        self.session_db.clear_session(self.session_id)
        self.state = {"messages": []}
        self.monitor.log_event("state_cleared", {"session_id": self.session_id})
    
    def _initialize_graph(self):
        """Assembles the LangGraph instance."""
        self.monitor.log_event("graph_build_start", {"agent_name": self.config.get('name')})
        
        provider = ToolProvider(
            workspace_path=self.workspace_dir,
            retriever=self.get_retriever(),
            monitor=self.monitor
        )
        
        requested_tools = self.config.get("tools", [])
        agent_tools = provider.get_tools(requested_tools)

        provider_pref = self.config.get("provider")
        system_prompt = self.config.get("system_prompt", "You are a helpful assistant.")

        return create_agent_graph(
            tools=agent_tools,
            retriever=self.get_retriever(),
            system_prompt=system_prompt,
            monitor=self.monitor,
            preferred_provider=provider_pref
        )



    def _archive_session_as_markdown(self):
        """Formats the current session's history into a Markdown file from the database."""
        sessions_dir = self.jerry_dir / "sessions"
        sessions_dir.mkdir(exist_ok=True)
        
        # Close the session in database
        self.session_db.close_session(self.session_id)
        
        # Get session info
        session_info = self.session_db.get_session_info(self.session_id)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        archive_path = sessions_dir / f"{timestamp}.md"
        
        transcript = f"# Agent Session: {timestamp}\n\n"
        transcript += f"**Session ID**: `{self.session_id}`\n"
        transcript += f"**Agent**: {self.config.get('name')}\n"
        transcript += f"**Started**: {session_info.get('started_at')}\n"
        transcript += f"**Messages**: {session_info.get('message_count')}\n\n"
        transcript += "---\n\n"
        
        # Retrieve messages from database
        messages = self.session_db.get_session_messages(self.session_id)
        
        for msg in messages:
            if isinstance(msg, HumanMessage):
                transcript += f"**👤 You:**\n```text\n{msg.content}\n```\n\n"
            elif isinstance(msg, AIMessage):
                if hasattr(msg, 'tool_calls') and msg.tool_calls:
                    transcript += f"**🤖 {self.config.get('name')}:**\n"
                    for tc in msg.tool_calls:
                        args = json.dumps(tc.get('args', {}), indent=2)
                        transcript += f"- `Tool Call: {tc.get('name')}`\n  ```json\n{args}\n  ```\n"
                else:
                    transcript += f"**🤖 {self.config.get('name')}:**\n```text\n{msg.content}\n```\n\n"
            elif isinstance(msg, ToolMessage):
                tool_id = getattr(msg, 'tool_call_id', 'unknown')
                transcript += f"**🔧 Tool Output (`{tool_id}`):**\n```text\n{msg.content}\n```\n\n"
        
        archive_path.write_text(transcript, encoding="utf-8")
        self.monitor.log_event("session_archived", {"path": str(archive_path), "session_id": self.session_id})

    def get_retriever(self):
        """Returns a vectorstore retriever for this agent."""
        return self.vector_store_manager.get_retriever(
            top_k=int(self.config.get("retrieve_top_k", 5))
        )
        
    def _create_new_agent_scaffold(self, name: str, provider: str, system_prompt: Optional[str]):
        """Creates the necessary files and directories for a new agent."""
        self.jerry_dir.mkdir(parents=True, exist_ok=True)
        self.chroma_dir.mkdir(exist_ok=True)
        self.log_dir.mkdir(exist_ok=True)

        # Write config
        config = {
            "name": name,
            "provider": provider,
            "system_prompt": system_prompt or "You are a helpful assistant.",
            "retrieve_top_k": 5,
            "tools": ["file_tools", "knowledge_tools"]
        }
        with open(self.config_path, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)

        # Initialize SQLite databases (sessions and logs)
        try:
            from .database import SessionDatabase, LogDatabase
            # Create DB files and schema
            SessionDatabase(self.session_db_path)
            LogDatabase(self.log_db_path)
        except Exception:
            # If DB creation fails, fall back to ensuring files exist
            self.session_db_path.parent.mkdir(parents=True, exist_ok=True)
            self.session_db_path.touch(exist_ok=True)
            self.log_db_path.parent.mkdir(parents=True, exist_ok=True)
            self.log_db_path.touch(exist_ok=True)

        # Ensure sessions archive dir exists
        (self.jerry_dir / "sessions").mkdir(exist_ok=True)

